// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctoycqciacgctnaaaqbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0b3ljcWNpYWNnY3RuYWFhcWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDU5MTcsImV4cCI6MjA2OTUyMTkxN30.BlKiMK81RP-TN9kAlGPgWNhrNsHyee8buVxmM0xV4iU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});